#ifndef WEB_PAGE_H
#define WEB_PAGE_H

const char* html_page = 
"<!DOCTYPE html> \n"
"<html lang=\"nl\"> \n"
"<head> \n"
"    <meta charset=\"UTF-8\"> \n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> \n"
"    <title>Smart Home - Rolluiken & Lampen</title> \n"
"    <style> \n"
"        * { margin: 0; padding: 0; box-sizing: border-box; } \n"
"        body { \n"
"            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; \n"
"            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); \n"
"            min-height: 100vh; \n"
"            padding: 10px; \n"
"        } \n"
"         \n"
"        /* MOBIEL EERST - Nieuwe aanpak! */ \n"
"        .container { \n"
"            max-width: 900px; \n"
"            width: 95%; \n"
"            margin: 0 auto; \n"
"            display: flex; \n"
"            flex-direction: column; \n"
"            gap: 20px; \n"
"        } \n"
"         \n"
"        .section { \n"
"            background: rgba(255, 255, 255, 0.95); \n"
"            border-radius: 20px; \n"
"            padding: 25px; \n"
"            box-shadow: 0 15px 35px rgba(0,0,0,0.15); \n"
"            backdrop-filter: blur(15px); \n"
"            transition: transform 0.3s ease, box-shadow 0.3s ease; \n"
"            display: flex; \n"
"            flex-direction: column; \n"
"            gap: 25px; \n"
"            align-items: center; \n"
"        } \n"
"         \n"
" \n"
"\n"
"        /* HEADER IN CONTENT-HALF */ \n"
"        .content-header { \n"
"            width: 100%; \n"
"            display: flex; \n"
"            flex-direction: column; \n"
"            align-items: center; \n"
"            gap: 15px; \n"
"            margin-bottom: 15px; \n"
"        } \n"
"         \n"
"        .enable-domotica { \n"
"            display: flex; \n"
"            align-items: center; \n"
"            gap: 12px; \n"
"            font-size: 18px; \n"
"            font-weight: 700; \n"
"            color: #333; \n"
"        } \n"
"         \n"
"        .enable-domotica input[type=\"checkbox\"] { \n"
"            width: 28px; \n"
"            height: 28px; \n"
"            accent-color: #4CAF50; \n"
"            transform: scale(1.2); \n"
"        } \n"
"         \n"
"        .section-title { \n"
"            font-size: 24px; \n"
"            color: #333; \n"
"            text-align: center; \n"
"            font-weight: 700; \n"
"        } \n"
" \n"
"        .content-half { \n"
"            width: 100%; \n"
"            display: flex; \n"
"            flex-direction: column; \n"
"            align-items: center; \n"
"        } \n"
"         \n"
"        .controls { \n"
"            display: flex; \n"
"            gap: 12px; \n"
"            justify-content: center; \n"
"            margin-bottom: 20px; \n"
"            flex-wrap: wrap; \n"
"        } \n"
"         \n"
"        /* GROTE KNAPPEN VOOR TOUCH! */ \n"
"        .btn { \n"
"            padding: 18px 35px; \n"
"            border: none; \n"
"            border-radius: 50px; \n"
"            font-size: 18px; \n"
"            font-weight: 700; \n"
"            cursor: pointer; \n"
"            transition: all 0.3s ease; \n"
"            box-shadow: 0 8px 20px rgba(0,0,0,0.2); \n"
"            min-width: 120px; \n"
"            touch-action: manipulation; \n"
"        } \n"
"         \n"
"        .btn-open { background: linear-gradient(45deg, #4CAF50, #45a049); color: white; } \n"
"        .btn-close { background: linear-gradient(45deg, #f44336, #da190b); color: white; } \n"
"        .btn-keep { background: linear-gradient(45deg, #FF9800, #e68900); color: white; } \n"
"        .btn-full-on { background: linear-gradient(45deg, #2196F3, #1976D2); color: white; } \n"
"        .btn-full-off { background: linear-gradient(45deg, #9E9E9E, #757575); color: white; } \n"
"        .btn-set { background: linear-gradient(45deg, #9C27B0, #7B1FA2); color: white; } \n"
"         \n"
"     \n"
" \n"
"        .btn:disabled { \n"
"            opacity: 0.5; \n"
"            cursor: not-allowed; \n"
"            transform: none !important; \n"
"        } \n"
" \n"
"        .status-box { \n"
"            background: linear-gradient(45deg, #e3f2fd, #bbdefb); \n"
"            padding: 20px; \n"
"            border-radius: 20px; \n"
"            text-align: center; \n"
"            margin-bottom: 20px; \n"
"            font-size: 20px; \n"
"            font-weight: 700; \n"
"            color: #1976D2; \n"
"            transition: all 0.3s ease; \n"
"            width: 100%; \n"
"            box-shadow: 0 5px 15px rgba(0,0,0,0.1); \n"
"        } \n"
"         \n"
"        .slider-container { margin: 25px 0; width: 100%; } \n"
"        .slider { \n"
"            width: 100%;  \n"
"            height: 12px; \n"
"            border-radius: 8px; \n"
"            background: #e0e0e0; \n"
"            outline: none; \n"
"            margin: 20px 0; \n"
"        } \n"
"        .slider::-webkit-slider-thumb { \n"
"            -webkit-appearance: none; \n"
"            appearance: none; \n"
"            width: 35px; \n"
"            height: 35px; \n"
"            border-radius: 50%; \n"
"            background: linear-gradient(45deg, #2196F3, #1976D2); \n"
"            cursor: pointer; \n"
"            box-shadow: 0 8px 20px rgba(0,0,0,0.3); \n"
"        } \n"
"         \n"
"        .slider-label { \n"
"            display: flex; \n"
"            justify-content: space-between; \n"
"            font-size: 16px; \n"
"            color: #666; \n"
"            margin-bottom: 10px; \n"
"            font-weight: 600; \n"
"        } \n"
"         \n"
"        .checkbox-group { \n"
"            display: flex; \n"
"            flex-direction: column; \n"
"            gap: 18px; \n"
"            margin: 25px 0; \n"
"            width: 100%; \n"
"        } \n"
"        .checkbox-item { \n"
"            display: flex; \n"
"            align-items: center; \n"
"            gap: 15px; \n"
"            font-size: 18px; \n"
"            padding: 12px; \n"
"            background: rgba(255,255,255,0.5); \n"
"            border-radius: 15px; \n"
"        } \n"
"        .checkbox-item input[type=\"checkbox\"] { \n"
"            width: 28px; \n"
"            height: 28px; \n"
"            accent-color: #2196F3; \n"
"        } \n"
"         \n"
"        .time-inputs { \n"
"            display: flex; \n"
"            flex-wrap: wrap; \n"
"            align-items: center; \n"
"            justify-content: center; \n"
"            gap: 15px; \n"
"            margin: 25px 0; \n"
"            width: 100%; \n"
"        } \n"
"        .time-input { \n"
"            display: flex; \n"
"            flex-direction: column; \n"
"            align-items: center; \n"
"        } \n"
"        .time-input label { \n"
"            font-size: 14px; \n"
"            color: #666; \n"
"            margin-bottom: 8px; \n"
"            font-weight: 600; \n"
"        } \n"
"        .time-input input { \n"
"            padding: 15px; \n"
"            border: 3px solid #e0e0e0; \n"
"            border-radius: 15px; \n"
"            font-size: 18px; \n"
"            text-align: center; \n"
"            width: 100%; \n"
"            background: white; \n"
"        } \n"
"         \n"
"        .sun-controls { \n"
"            background: linear-gradient(45deg, #fff3e0, #ffe0b2); \n"
"            padding: 25px; \n"
"            border-radius: 20px; \n"
"            margin: 20px 0; \n"
"            width: 100%; \n"
"            text-align: center; \n"
"        } \n"
"         \n"
"        .lamp-controls {  \n"
"            display: flex; \n"
"            flex-direction: column; \n"
"            gap: 25px; \n"
"            width: 100%; \n"
"            align-items: center; \n"
"        } \n"
" \n"
"        @media (min-width: 768px) { \n"
"            body { padding: 20px; } \n"
"            .container { gap: 30px; } \n"
"            .section { \n"
"                flex-direction: row; \n"
"                padding: 30px; \n"
"                gap: 40px; \n"
"                align-items: flex-start; \n"
"            } \n"
"            .content-half {  \n"
"                width: 100%; \n"
"                align-items: center; \n"
"            } \n"
"            .section-title { font-size: 28px; } \n"
"            .btn { padding: 15px 30px; font-size: 16px; } \n"
"            .time-inputs { grid-template-columns: repeat(3, 1fr); } \n"
"            .content-header { \n"
"                flex-direction: row; \n"
"                justify-content: space-between; \n"
"                align-items: center; \n"
"            } \n"
"        } \n"
"         \n"
"        @media (min-width: 480px) and (max-width: 767px) { \n"
"            .time-inputs { grid-template-columns: repeat(3, 1fr); } \n"
"        } \n"
" \n"
"        .ip-box{ \n"
"    width:100%; \n"
"    display:flex; \n"
"    align-items:center; \n"
"    gap:12px; \n"
"    margin-bottom:20px; \n"
"    padding:12px 15px; \n"
"    border-radius:15px; \n"
"    background:#eef3f8; \n"
"    } \n"
" \n"
"    .ip-box input{ \n"
"        flex:1; \n"
"        padding:10px 15px; \n"
"        border:2px solid #ccc; \n"
"        border-radius:10px; \n"
"        font-size:16px; \n"
"    } \n"
" \n"
"    .keep-distance{ \n"
"    display:flex; \n"
"    align-items:center; \n"
"    justify-content:center; \n"
"    gap:12px; \n"
"    width:100%; \n"
"    margin-bottom:15px; \n"
"    padding:12px; \n"
"    background:rgba(255,255,255,.6); \n"
"    border-radius:15px; \n"
"} \n"
" \n"
".keep-distance label{ \n"
"    font-size:17px; \n"
"    font-weight:600; \n"
"    color:#333; \n"
"} \n"
" \n"
".keep-distance input{ \n"
"    width:90px; \n"
"    padding:8px 12px; \n"
"    border:2px solid #ddd; \n"
"    border-radius:10px; \n"
"    font-size:18px; \n"
"    text-align:center; \n"
"} \n"
"</style> \n"
"</head> \n"
"<body> \n"
"    <div class=\"container\"> \n"
"         \n"
"        <div class=\"section\"> \n"
"            <div class=\"content-half\"> \n"
"               <div class=\"content-header\"> \n"
"                    <div class=\"enable-domotica\"> \n"
"                        <input type=\"checkbox\" id=\"enableRolluik\" checked onchange=\"toggleRolluikControls(this.checked)\"> \n"
"                        <label for=\"enableRolluik\">Enable Domotica</label> \n"
"                    </div> \n"
"                    <h2 class=\"section-title\">🏠 Rolluiken</h2> \n"
"                </div> \n"
"                 \n"
"                <div class=\"ip-box\"> \n"
"                    <label for=\"rolluikIP\"><strong>Rolluik IP:</strong></label> \n"
" \n"
"                    <input type=\"text\" placeholder=\"192.168.1.100\" inputmode=\"decimal\" onchange=\"setRolluikIP(this.value)\" \n"
"                    > \n"
"                </div> \n"
"                 \n"
"                <div class=\"controls\"> \n"
"                    <button class=\"btn btn-open\" onclick=\"setRolluik('open')\">Open</button> \n"
"                    <button class=\"btn btn-close\" onclick=\"setRolluik('dicht')\">Dicht</button> \n"
"                    <button class=\"btn btn-keep\" onclick=\"setRolluik('keep')\">Keepstand</button> \n"
"                </div> \n"
"                <div class=\"status-box\" id=\"rolluikStatus\">🟡 KEEP</div> \n"
"                <div class=\"keep-distance\"> \n"
"                    <label for=\"keepDistance\"> Keep afstand</label> \n"
"                    <input  \n"
"                        type=\"number\"  \n"
"                        id=\"keepDistance\"  \n"
"                        min=\"0\"  \n"
"                        max=\"1000\"  \n"
"                        value=\"300\"  \n"
"                        onchange=\"setKeepDistance(this.value)\"> \n"
"                    <span>cm</span> \n"
"                </div> \n"
"                <div class=\"sun-controls\"> \n"
"                    <h3 style=\"margin-bottom: 15px; font-size: 20px;\">☀️ Timer</h3> \n"
"                    <label class=\"checkbox-item\"><input type=\"checkbox\" id=\"sunOpen\" onchange=\"toggleSunUp(this.checked)\"> Openen in de ochtend</label> \n"
"                    <label class=\"checkbox-item\"><input type=\"checkbox\" id=\"sunClose\" onchange=\"toggleSunDown(this.checked)\"> Sluiten in de avond</label> \n"
"                    <div class=\"time-inputs\"> \n"
"                    <div class=\"time-input\"><label>Keep</label><input type=\"time\" value=\"07:50\" onchange=\"KeepTijd(this.value)\"></div> \n"
"                    <div class=\"time-input\"><label>Open</label><input type=\"time\" value=\"08:00\" onchange=\"OpenTijd(this.value)\"></div> \n"
"                    <div class=\"time-input\"><label>Dicht</label><input type=\"time\" value=\"22:00\" onchange=\"DichtTijd(this.value)\"></div> \n"
"                </div> \n"
"                </div> \n"
"                 \n"
"            </div> \n"
"        </div> \n"
" \n"
"         \n"
"        <div class=\"section\"> \n"
"            <div class=\"content-half\"> \n"
"                <div class=\"content-header\"> \n"
"                    <div class=\"enable-domotica\"> \n"
"                        <input type=\"checkbox\" id=\"enableLamp1\" checked onchange=\"toggleLamp1Controls(this.checked)\"> \n"
"                        <label for=\"enableLamp1\">Enable Domotica</label> \n"
"                    </div> \n"
"                    <h2 class=\"section-title\">💡 Groot Licht</h2> \n"
"                </div> \n"
" \n"
"                <div class=\"ip-box\"> \n"
"                    <label for=\"rolluikIP\"><strong>Groot Licht IP:</strong></label> \n"
" \n"
"                    <input type=\"text\" placeholder=\"192.168.1.100\" inputmode=\"decimal\" onchange=\"setLamp1IP(this.value)\" \n"
"                    > \n"
"                </div> \n"
"               \n"
"                <div class=\"status-box\" id=\"lamp1Status\">🔴 UIT</div> \n"
"                <div class=\"lamp-controls\"> \n"
"                    <div class=\"slider-container\"> \n"
"                        <div class=\"slider-label\"> \n"
"                            <span>Helderheid</span> \n"
"                            <span id=\"lamp1Brightness\">0%</span> \n"
"                        </div> \n"
"                        <input type=\"range\" min=\"0\" max=\"100\" value=\"0\" class=\"slider\" id=\"lamp1Slider\" oninput=\"updateLamp1Status(this.value)\"> \n"
"                    </div> \n"
"                </div> \n"
"                <div class=\"checkbox-group\"> \n"
"                        <label class=\"checkbox-item\"><input type=\"checkbox\" id=\"presence1\" onchange=\"togglePre1(this.checked)\"> Aan bij aanwezigheid</label> \n"
"                </div> \n"
"            </div> \n"
"        </div> \n"
" \n"
"         \n"
"        <div class=\"section\"> \n"
"            <div class=\"content-half\"> \n"
"                <div class=\"content-header\"> \n"
"                    <div class=\"enable-domotica\"> \n"
"                        <input type=\"checkbox\" id=\"enableLamp2\" checked onchange=\"toggleLamp2Controls(this.checked)\"> \n"
"                        <label for=\"enableLamp2\">Enable Domotica</label> \n"
"                    </div> \n"
"                    <h2 class=\"section-title\">💡 Nacht Lampje</h2> \n"
"                </div> \n"
" \n"
"                <div class=\"ip-box\"> \n"
"                    <label for=\"rolluikIP\"><strong>Nacht Lampje IP:</strong></label> \n"
" \n"
"                    <input type=\"text\" placeholder=\"192.168.1.100\" inputmode=\"decimal\" onchange=\"setLamp2IP(this.value)\" \n"
"                    > \n"
"                </div> \n"
"                \n"
"                <div class=\"status-box\" id=\"lamp2Status\">🔴 UIT</div> \n"
"                <div class=\"lamp-controls\"> \n"
"                    <div class=\"slider-container\"> \n"
"                        <div class=\"slider-label\"> \n"
"                            <span>Helderheid</span> \n"
"                            <span id=\"lamp2Brightness\">0%</span> \n"
"                        </div> \n"
"                        <input type=\"range\" min=\"0\" max=\"100\" value=\"0\" class=\"slider\" id=\"lamp2Slider\" oninput=\"updateLamp2Status(this.value)\"> \n"
"                    </div> \n"
"                </div> \n"
"                <div class=\"checkbox-group\"> \n"
"                        <label class=\"checkbox-item\"><input type=\"checkbox\" id=\"presence2\" onchange=\"togglePre2(this.checked)\"> Aan bij aanwezigheid</label> \n"
"                </div> \n"
"            </div> \n"
"        </div> \n"
" \n"
"                 \n"
"        <div class=\"section\" id=\"getPosSection\"> \n"
"            <div class=\"content-half\"> \n"
" \n"
"                 \n"
"                <div class=\"content-header\"> \n"
"                    <div class=\"enable-domotica\"> \n"
"                        <input type=\"checkbox\" id=\"GetPosEn\" checked onchange=\"toggleGetPos(this.checked)\"> \n"
"                        <label for=\"GetPosEn\">Enable Domotica</label> \n"
"                    </div> \n"
"                    <button class=\"btn btn-set\" onclick=\"fetch('/set?getPosition=1')\"> \n"
"                        📍 Get Position \n"
"                    </button> \n"
"                </div> \n"
" \n"
"                <div class=\"ip-box\"> \n"
"                    <label for=\"rolluikIP\"><strong>mmWave IP:</strong></label> \n"
" \n"
"                    <input type=\"text\" placeholder=\"192.168.1.100\" inputmode=\"decimal\" onchange=\"setMmWaveIP(this.value)\" \n"
"                    > \n"
"                </div> \n"
"         \n"
" \n"
"                 \n"
"                <div style=\"display:flex; flex-direction:column; gap:20px; width:100%;\"> \n"
" \n"
"                     \n"
"                    <div class=\"checkbox-group\" style=\"width:100%; background:rgba(255,255,255,0.6); padding:15px; border-radius:15px;\"> \n"
"                        <h3 style=\"margin-bottom:10px;\">Rolluiken</h3> \n"
"                        <label class=\"checkbox-item\"><input type=\"radio\"  name=\"rolluik\" onchange=\"setPosRolluik('open')\"> Open</label> \n"
"                        <label class=\"checkbox-item\"><input type=\"radio\"  name=\"rolluik\" onchange=\"setPosRolluik('dicht')\"> Dicht</label> \n"
"                        <label class=\"checkbox-item\"><input type=\"radio\"  name=\"rolluik\" onchange=\"setPosRolluik('keep')\"> Keep</label> \n"
"                    </div> \n"
" \n"
"                     \n"
"                    <div class=\"checkbox-group\" style=\"width:100%; background:rgba(255,255,255,0.6); padding:15px; border-radius:15px;\"> \n"
"                        <h3 style=\"margin-bottom:10px;\">Groot Licht</h3> \n"
"                        <div class=\"slider-container\"> \n"
"                        <div class=\"slider-label\"> \n"
"                            <span>Helderheid</span> \n"
"                            <span id=\"setPosLamp1Brightness\">75%</span> \n"
"                        </div> \n"
"                        <input type=\"range\" min=\"0\" max=\"100\" value=\"75\" class=\"slider\" id=\"setPosLamp1Slider\" onchange=\"updatePosLamp1(this.value)\"> \n"
"                    </div> \n"
"                    </div> \n"
" \n"
"                     \n"
"                    <div class=\"checkbox-group\" style=\"width:100%; background:rgba(255,255,255,0.6); padding:15px; border-radius:15px;\"> \n"
"                        <h3 style=\"margin-bottom:10px;\">Nacht Lampje</h3> \n"
"                        <div class=\"slider-container\"> \n"
"                        <div class=\"slider-label\"> \n"
"                            <span>Helderheid</span> \n"
"                            <span id=\"setPosLamp2Brightness\">75%</span> \n"
"                        </div> \n"
"                        <input type=\"range\" min=\"0\" max=\"100\" value=\"75\" class=\"slider\" id=\"setPosLamp2Slider\" onchange=\"updatePosLamp2(this.value)\"> \n"
"                    </div> \n"
"                    </div> \n"
" \n"
"                </div> \n"
"            </div> \n"
"        </div> \n"
"    </div> \n"
" \n"
"     \n"
" \n"
"<script> \n"
"    window.addEventListener(\"DOMContentLoaded\", () => { \n"
" \n"
"    // alle checkboxes op pagina \n"
"    const checkboxes = document.querySelectorAll(\"input[type='checkbox']\"); \n"
" \n"
"    checkboxes.forEach(cb => { \n"
"        // triggert je bestaande onchange handlers \n"
"        cb.dispatchEvent(new Event(\"change\")); \n"
"    }); \n"
" \n"
"}); \n"
" \n"
"function toggleRolluikControls(enabled) { \n"
"    const section = document.getElementById(\"enableRolluik\").closest(\".section\"); \n"
"    const controls = section.querySelectorAll( \n"
"        \".sun-controls input, .time-inputs input\" \n"
"    ); \n"
" \n"
"    fetch('/set?rolluikEnable=' + (enabled ? '1' : '0')); \n"
" \n"
"    controls.forEach(control => { \n"
"        control.disabled = !enabled; \n"
"        control.style.opacity = enabled ? '1' : '0.5'; \n"
" \n"
"        if (control.tagName === 'BUTTON') { \n"
"            control.style.cursor = enabled ? 'pointer' : 'not-allowed'; \n"
"        } \n"
"    }); \n"
"} \n"
" \n"
"function setRolluik(action) { \n"
"    fetch('/set?rolluikAction=' + action); \n"
"} \n"
" \n"
" \n"
"function setKeepDistance(distance){ \n"
"    fetch(\"/set?keepDistance=\" + distance); \n"
"} \n"
" \n"
"function toggleSunUp(enable) { \n"
"    fetch('/set?rolluikSunUp=' + (enable ? '1' : '0')); \n"
"} \n"
" \n"
"function toggleSunDown(enable) { \n"
"    fetch('/set?rolluikSunDown=' + (enable ? '1' : '0')); \n"
"} \n"
" \n"
"function OpenTijd(tijd) { \n"
"    fetch('/set?rolluikTimeOpen=' + tijd); \n"
"} \n"
" \n"
"function DichtTijd(tijd) { \n"
"    fetch('/set?rolluikTimeClose=' + tijd); \n"
"} \n"
" \n"
"function KeepTijd(tijd) { \n"
"    fetch('/set?rolluikTimeKeep=' + tijd); \n"
"} \n"
" \n"
"function toggleLamp1Controls(enabled) { \n"
"    const section = document.getElementById(\"enableLamp1\").closest(\".section\"); \n"
"    const controls = section.querySelectorAll(\".checkbox-group input\"); \n"
" \n"
"    fetch('/set?EnLamp1=' + (enabled ? '1' : '0')); \n"
" \n"
"    controls.forEach(control => { \n"
"        control.disabled = !enabled; \n"
"        control.style.opacity = enabled ? '1' : '0.5'; \n"
"    }); \n"
"} \n"
" \n"
"function updateLamp1Status(value) { \n"
"    document.getElementById('lamp1Brightness').textContent = value + '%'; \n"
"    const status = document.getElementById('lamp1Status'); \n"
" \n"
"    fetch('/set?BrLamp1=' + value); \n"
" \n"
"    if (value == 0) { \n"
"        status.textContent = '🔴 UIT'; \n"
"        status.style.background = 'linear-gradient(45deg, #e0e0e0, #bdbdbd)'; \n"
"        status.style.color = '#616161'; \n"
"    } \n"
"    else if (value == 100) { \n"
"        status.textContent = '💡 VOLLEDIG AAN'; \n"
"        status.style.background = 'linear-gradient(45deg, #e3f2fd, #bbdefb)'; \n"
"        status.style.color = '#1976D2'; \n"
"    } \n"
"    else { \n"
"        status.textContent = '💡 ' + value + '%'; \n"
"        status.style.background = 'linear-gradient(45deg, #f3e5f5, #e1bee7)'; \n"
"        status.style.color = '#7b1fa2'; \n"
"    } \n"
"} \n"
" \n"
"function togglePre1(enable) { \n"
"    fetch('/set?PreLamp1=' + (enable ? 'PreOn1' : 'PreOff1')); \n"
"} \n"
" \n"
"function toggleLamp2Controls(enabled) { \n"
"    const section = document.getElementById(\"enableLamp2\").closest(\".section\"); \n"
"    const controls = section.querySelectorAll(\".checkbox-group input\"); \n"
" \n"
"    fetch('/set?EnLamp2=' + (enabled ? '1' : '0')); \n"
" \n"
"    controls.forEach(control => { \n"
"        control.disabled = !enabled; \n"
"        control.style.opacity = enabled ? '1' : '0.5'; \n"
"    }); \n"
"} \n"
" \n"
"function updateLamp2Status(value) { \n"
"    document.getElementById('lamp2Brightness').textContent = value + '%'; \n"
"    const status = document.getElementById('lamp2Status'); \n"
" \n"
"    fetch('/set?BrLamp2=' + value); \n"
" \n"
"    if (value == 0) { \n"
"        status.textContent = '🔴 UIT'; \n"
"        status.style.background = 'linear-gradient(45deg, #e0e0e0, #bdbdbd)'; \n"
"        status.style.color = '#616161'; \n"
"    } \n"
"    else if (value == 100) { \n"
"        status.textContent = '💡 VOLLEDIG AAN'; \n"
"        status.style.background = 'linear-gradient(45deg, #e3f2fd, #bbdefb)'; \n"
"        status.style.color = '#1976D2'; \n"
"    } \n"
"    else { \n"
"        status.textContent = '💡 ' + value + '%'; \n"
"        status.style.background = 'linear-gradient(45deg, #f3e5f5, #e1bee7)'; \n"
"        status.style.color = '#7b1fa2'; \n"
"    } \n"
"} \n"
" \n"
"function togglePre2(enable) { \n"
"    fetch('/set?PreLamp2=' + (enable ? 'PreOn2' : 'PreOff2')); \n"
"} \n"
" \n"
"function toggleGetPos(enabled) { \n"
"    const section = document.getElementById('getPosSection'); \n"
" \n"
"    const controls = section.querySelectorAll( \n"
"        'input[name=\"rolluik\"], input[type=\"range\"]' \n"
"    ); \n"
" \n"
"    fetch('/set?setPosEnable=' + (enabled ? '1' : '0')); \n"
" \n"
"    controls.forEach(control => { \n"
"        control.disabled = !enabled; \n"
" \n"
"        const parent = control.closest('.checkbox-group'); \n"
"        if (parent) { \n"
"            parent.style.opacity = enabled ? '1' : '0.4'; \n"
"            parent.style.pointerEvents = enabled ? 'auto' : 'none'; \n"
"        } \n"
"    }); \n"
"} \n"
" \n"
"function updatePosLamp1(value) { \n"
"    document.getElementById('setPosLamp1Brightness').textContent = value + '%'; \n"
"    fetch('/set?SetposLamp1=' + value); \n"
"} \n"
" \n"
"function updatePosLamp2(value) { \n"
"    document.getElementById('setPosLamp2Brightness').textContent = value + '%'; \n"
"    fetch('/set?SetposLamp2=' + value); \n"
"} \n"
" \n"
" \n"
"function setRolluikIP(ip) { \n"
"    fetch('/set?rolluikIP=' + encodeURIComponent(ip)); \n"
"} \n"
" \n"
"function setLamp1IP(ip) { \n"
"    fetch('/set?lamp1IP=' + encodeURIComponent(ip)); \n"
"} \n"
" \n"
"function setLamp2IP(ip) { \n"
"    fetch('/set?lamp2IP=' + encodeURIComponent(ip)); \n"
"} \n"
" \n"
"function setMmWaveIP(ip) { \n"
"    fetch('/set?mmWaveIP=' + encodeURIComponent(ip)); \n"
"} \n"
" \n"
" \n"
"function updateRolluikStatus() { \n"
"    const look = document.getElementById('rolluikStatus'); \n"
"fetch(\"/status\")  \n"
".then(response => response.text())  \n"
".then(status => { status = status.trim();  \n"
"    if (status === \"OPEN\") { \n"
"        look.textContent = \"🟢 OPEN\"; \n"
"        look.style.background = \"linear-gradient(45deg, #c8e6c9, #a5d6a7)\"; \n"
"        look.style.color = \"#2e7d32\";  \n"
"    }  \n"
"    if (status === \"DICHT\") {  \n"
"        look.textContent = \"🔴 DICHT\"; \n"
"        look.style.background = \"linear-gradient(45deg, #ffcdd2, #ef9a9a)\"; \n"
"        look.style.color = \"#c62828\"; \n"
"    }  \n"
"    if (status === \"KEEP\") { \n"
"        look.textContent = \"🟡 KEEP\"; \n"
"        look.style.background = \"linear-gradient(45deg, #fff9c4, #ffe082)\"; \n"
"        look.style.color = \"#f57f17\"; \n"
"    }  \n"
"    if (status === \"IDLE\") { \n"
"        look.textContent = \"⚪ IDLE\"; \n"
"        look.style.background = \"linear-gradient(45deg, #eceff1, #cfd8dc)\"; \n"
"        look.style.color = \"#455a64\"; \n"
"    } \n"
"    });  \n"
"}  \n"
"updateRolluikStatus(); \n"
"setInterval(updateRolluikStatus, 1000);  \n"
"</script> \n"
" \n"
" \n"
"</body> \n"
"</html>";

#endif